version: 2.1

jobs:
  save_hello_world_output:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          command: echo "text to output here" > output.txt
    root: /tmp/workspace
    paths: output.txt
  print_output_file:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: /tmp/workspace
          
workflows:
  save-hello-workflow:
    jobs:
      - save_hello_world_output
      - print_output_file
